components:
  - changed-files:
      - any-glob-to-any-file:
          - packages/*.component/*
          - packages/*.component/**/*

systems:
  - changed-files:
      - any-glob-to-any-file:
          - packages/*.system/*
          - packages/*.system/**/*
