components:
  - changed-files:
      - any-glob-to-any-file:
          - src/*.component/*
          - src/*.component/**/*

systems:
  - changed-files:
      - any-glob-to-any-file:
          - src/*.system/*
          - src/*.system/**/*
