catalogs:
  ci:
    '@nanoforge-dev/actions': ^1.3.0
    '@commitlint/cli': ^20.5.0
    '@commitlint/config-conventional': ^20.5.0
    lint-staged: ^16.4.0
    husky: ^9.1.7
  core:
    '@nanoforge-dev/common': ^1.1.0
    '@nanoforge-dev/ecs-lib': ^1.1.2
    '@nanoforge-dev/ecs-server': ^1.1.3
    '@nanoforge-dev/input': ^1.0.2
    '@nanoforge-dev/graphics-2d': ^1.0.2
    '@nanoforge-dev/network-client': ^1.2.0
    '@nanoforge-dev/network-server': ^1.2.0
    typescript: ^6.0.2
  lint:
    '@eslint/js': ^10.0.1
    '@nanoforge-dev/utils-eslint-config': ^1.0.2
    '@nanoforge-dev/utils-prettier-config': ^1.0.2
    '@trivago/prettier-plugin-sort-imports': ^6.0.2
    eslint: ^10.1.0
    eslint-config-prettier: ^10.1.8
    eslint-formatter-pretty: ^7.0.0
    eslint-plugin-format: ^2.0.1
    eslint-plugin-prettier: ^5.5.5
    globals: ^17.3.0
    prettier: ^3.8.1
    typescript-eslint: ^8.59.1
  test:
    '@vitest/coverage-v8': ^4.1.2
    vitest: ^4.1.2
