import type { EditorComponentManifest } from "@nanoforge-dev/ecs-lib";
import { type InputEnum } from "@nanoforge-dev/input";

export class MoveController2D {
  name = this.constructor.name;

  constructor(
    public speedUp: number,
    public speedDown: number,
    public speedLeft: number,
    public speedRight: number,
    public keyUp?: InputEnum,
    public keyDown?: InputEnum,
    public keyLeft?: InputEnum,
    public keyRight?: InputEnum,
  ) {}
}

// * Required to generate code
export default MoveController2D.name;

// * Required for the editor to display the component and generate code
export const EDITOR_COMPONENT_MANIFEST: EditorComponentManifest = {
  name: "MoveController2D",
  description:
    "Allow control with 4 directional movement of en entity, select speed and keys to use",
  params: [
    {
      type: "number",
      name: "speedUp",
      description: "Speed going up in pixels per second",
      example: 4.2,
      default: 50,
    },
    {
      type: "number",
      name: "speedDown",
      description: "Speed going down in pixels per second",
      example: 4.2,
      default: 50,
    },
    {
      type: "number",
      name: "speedLeft",
      description: "Speed going left in pixels per second",
      example: 4.2,
      default: 50,
    },
    {
      type: "number",
      name: "speedRight",
      description: "Speed going right in pixels per second",
      example: 4.2,
      default: 50,
    },
    {
      name: "keyUp",
      type: "string",
      optional: true,
      enum: [
        "Escape",
        "Digit1",
        "Digit2",
        "Digit3",
        "Digit4",
        "Digit5",
        "Digit6",
        "Digit7",
        "Digit8",
        "Digit9",
        "Digit0",
        "Minus",
        "Equal",
        "Backspace",
        "Tab",
        "KeyQ",
        "KeyW",
        "KeyE",
        "KeyR",
        "KeyT",
        "KeyY",
        "KeyU",
        "KeyI",
        "KeyO",
        "KeyP",
        "BracketLeft",
        "BracketRight",
        "Enter",
        "ControlLeft",
        "KeyA",
        "KeyS",
        "KeyD",
        "KeyF",
        "KeyG",
        "KeyH",
        "KeyJ",
        "KeyK",
        "KeyL",
        "Semicolon",
        "Quote",
        "Backquote",
        "ShiftLeft",
        "Backslash",
        "KeyZ",
        "KeyX",
        "KeyC",
        "KeyV",
        "KeyB",
        "KeyN",
        "KeyM",
        "Comma",
        "Period",
        "Slash",
        "ShiftRight",
        "NumpadMultiply",
        "AltLeft",
        "Space",
        "CapsLock",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "Pause",
        "ScrollLock",
        "Numpad7",
        "Numpad8",
        "Numpad9",
        "NumpadSubtract",
        "Numpad4",
        "Numpad5",
        "Numpad6",
        "NumpadAdd",
        "Numpad1",
        "Numpad2",
        "Numpad3",
        "Numpad0",
        "NumpadDecimal",
        "IntlBackslash",
        "F11",
        "F12",
        "NumpadEqual",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "KanaMode",
        "Lang2",
        "Lang1",
        "IntlRo",
        "F24",
        "Convert",
        "NonConvert",
        "IntlYen",
        "NumpadComma",
        "MediaTrackPrevious",
        "MediaTrackNext",
        "NumpadEnter",
        "ControlRight",
        "AudioVolumeMute",
        "LaunchApp2",
        "MediaPlayPause",
        "MediaStop",
        "BrowserHome",
        "NumpadDivide",
        "PrintScreen",
        "AltRight",
        "NumLock",
        "Home",
        "ArrowUp",
        "PageUp",
        "ArrowLeft",
        "ArrowRight",
        "End",
        "ArrowDown",
        "PageDown",
        "Insert",
        "Delete",
        "MetaLeft",
        "MetaRight",
        "ContextMenu",
        "Power",
        "BrowserSearch",
        "BrowserFavorites",
        "BrowserRefresh",
        "BrowserStop",
        "BrowserForward",
        "BrowserBack",
        "LaunchApp1",
        "LaunchMail",
      ],
      description: "Key to press to go up",
      example: "ArrowUp",
      default: "ArrowUp",
    },
    {
      name: "keyDown",
      type: "string",
      optional: true,
      enum: [
        "Escape",
        "Digit1",
        "Digit2",
        "Digit3",
        "Digit4",
        "Digit5",
        "Digit6",
        "Digit7",
        "Digit8",
        "Digit9",
        "Digit0",
        "Minus",
        "Equal",
        "Backspace",
        "Tab",
        "KeyQ",
        "KeyW",
        "KeyE",
        "KeyR",
        "KeyT",
        "KeyY",
        "KeyU",
        "KeyI",
        "KeyO",
        "KeyP",
        "BracketLeft",
        "BracketRight",
        "Enter",
        "ControlLeft",
        "KeyA",
        "KeyS",
        "KeyD",
        "KeyF",
        "KeyG",
        "KeyH",
        "KeyJ",
        "KeyK",
        "KeyL",
        "Semicolon",
        "Quote",
        "Backquote",
        "ShiftLeft",
        "Backslash",
        "KeyZ",
        "KeyX",
        "KeyC",
        "KeyV",
        "KeyB",
        "KeyN",
        "KeyM",
        "Comma",
        "Period",
        "Slash",
        "ShiftRight",
        "NumpadMultiply",
        "AltLeft",
        "Space",
        "CapsLock",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "Pause",
        "ScrollLock",
        "Numpad7",
        "Numpad8",
        "Numpad9",
        "NumpadSubtract",
        "Numpad4",
        "Numpad5",
        "Numpad6",
        "NumpadAdd",
        "Numpad1",
        "Numpad2",
        "Numpad3",
        "Numpad0",
        "NumpadDecimal",
        "IntlBackslash",
        "F11",
        "F12",
        "NumpadEqual",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "KanaMode",
        "Lang2",
        "Lang1",
        "IntlRo",
        "F24",
        "Convert",
        "NonConvert",
        "IntlYen",
        "NumpadComma",
        "MediaTrackPrevious",
        "MediaTrackNext",
        "NumpadEnter",
        "ControlRight",
        "AudioVolumeMute",
        "LaunchApp2",
        "MediaPlayPause",
        "MediaStop",
        "BrowserHome",
        "NumpadDivide",
        "PrintScreen",
        "AltRight",
        "NumLock",
        "Home",
        "ArrowUp",
        "PageUp",
        "ArrowLeft",
        "ArrowRight",
        "End",
        "ArrowDown",
        "PageDown",
        "Insert",
        "Delete",
        "MetaLeft",
        "MetaRight",
        "ContextMenu",
        "Power",
        "BrowserSearch",
        "BrowserFavorites",
        "BrowserRefresh",
        "BrowserStop",
        "BrowserForward",
        "BrowserBack",
        "LaunchApp1",
        "LaunchMail",
      ],
      description: "Key to press to go down",
      example: "ArrowDown",
      default: "ArrowDown",
    },
    {
      name: "keyLeft",
      type: "string",
      optional: true,
      enum: [
        "Escape",
        "Digit1",
        "Digit2",
        "Digit3",
        "Digit4",
        "Digit5",
        "Digit6",
        "Digit7",
        "Digit8",
        "Digit9",
        "Digit0",
        "Minus",
        "Equal",
        "Backspace",
        "Tab",
        "KeyQ",
        "KeyW",
        "KeyE",
        "KeyR",
        "KeyT",
        "KeyY",
        "KeyU",
        "KeyI",
        "KeyO",
        "KeyP",
        "BracketLeft",
        "BracketRight",
        "Enter",
        "ControlLeft",
        "KeyA",
        "KeyS",
        "KeyD",
        "KeyF",
        "KeyG",
        "KeyH",
        "KeyJ",
        "KeyK",
        "KeyL",
        "Semicolon",
        "Quote",
        "Backquote",
        "ShiftLeft",
        "Backslash",
        "KeyZ",
        "KeyX",
        "KeyC",
        "KeyV",
        "KeyB",
        "KeyN",
        "KeyM",
        "Comma",
        "Period",
        "Slash",
        "ShiftRight",
        "NumpadMultiply",
        "AltLeft",
        "Space",
        "CapsLock",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "Pause",
        "ScrollLock",
        "Numpad7",
        "Numpad8",
        "Numpad9",
        "NumpadSubtract",
        "Numpad4",
        "Numpad5",
        "Numpad6",
        "NumpadAdd",
        "Numpad1",
        "Numpad2",
        "Numpad3",
        "Numpad0",
        "NumpadDecimal",
        "IntlBackslash",
        "F11",
        "F12",
        "NumpadEqual",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "KanaMode",
        "Lang2",
        "Lang1",
        "IntlRo",
        "F24",
        "Convert",
        "NonConvert",
        "IntlYen",
        "NumpadComma",
        "MediaTrackPrevious",
        "MediaTrackNext",
        "NumpadEnter",
        "ControlRight",
        "AudioVolumeMute",
        "LaunchApp2",
        "MediaPlayPause",
        "MediaStop",
        "BrowserHome",
        "NumpadDivide",
        "PrintScreen",
        "AltRight",
        "NumLock",
        "Home",
        "ArrowUp",
        "PageUp",
        "ArrowLeft",
        "ArrowRight",
        "End",
        "ArrowDown",
        "PageDown",
        "Insert",
        "Delete",
        "MetaLeft",
        "MetaRight",
        "ContextMenu",
        "Power",
        "BrowserSearch",
        "BrowserFavorites",
        "BrowserRefresh",
        "BrowserStop",
        "BrowserForward",
        "BrowserBack",
        "LaunchApp1",
        "LaunchMail",
      ],
      description: "Key to press to go left",
      example: "ArrowLeft",
      default: "ArrowLeft",
    },
    {
      name: "keyRight",
      type: "string",
      optional: true,
      enum: [
        "Escape",
        "Digit1",
        "Digit2",
        "Digit3",
        "Digit4",
        "Digit5",
        "Digit6",
        "Digit7",
        "Digit8",
        "Digit9",
        "Digit0",
        "Minus",
        "Equal",
        "Backspace",
        "Tab",
        "KeyQ",
        "KeyW",
        "KeyE",
        "KeyR",
        "KeyT",
        "KeyY",
        "KeyU",
        "KeyI",
        "KeyO",
        "KeyP",
        "BracketLeft",
        "BracketRight",
        "Enter",
        "ControlLeft",
        "KeyA",
        "KeyS",
        "KeyD",
        "KeyF",
        "KeyG",
        "KeyH",
        "KeyJ",
        "KeyK",
        "KeyL",
        "Semicolon",
        "Quote",
        "Backquote",
        "ShiftLeft",
        "Backslash",
        "KeyZ",
        "KeyX",
        "KeyC",
        "KeyV",
        "KeyB",
        "KeyN",
        "KeyM",
        "Comma",
        "Period",
        "Slash",
        "ShiftRight",
        "NumpadMultiply",
        "AltLeft",
        "Space",
        "CapsLock",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "Pause",
        "ScrollLock",
        "Numpad7",
        "Numpad8",
        "Numpad9",
        "NumpadSubtract",
        "Numpad4",
        "Numpad5",
        "Numpad6",
        "NumpadAdd",
        "Numpad1",
        "Numpad2",
        "Numpad3",
        "Numpad0",
        "NumpadDecimal",
        "IntlBackslash",
        "F11",
        "F12",
        "NumpadEqual",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "KanaMode",
        "Lang2",
        "Lang1",
        "IntlRo",
        "F24",
        "Convert",
        "NonConvert",
        "IntlYen",
        "NumpadComma",
        "MediaTrackPrevious",
        "MediaTrackNext",
        "NumpadEnter",
        "ControlRight",
        "AudioVolumeMute",
        "LaunchApp2",
        "MediaPlayPause",
        "MediaStop",
        "BrowserHome",
        "NumpadDivide",
        "PrintScreen",
        "AltRight",
        "NumLock",
        "Home",
        "ArrowUp",
        "PageUp",
        "ArrowLeft",
        "ArrowRight",
        "End",
        "ArrowDown",
        "PageDown",
        "Insert",
        "Delete",
        "MetaLeft",
        "MetaRight",
        "ContextMenu",
        "Power",
        "BrowserSearch",
        "BrowserFavorites",
        "BrowserRefresh",
        "BrowserStop",
        "BrowserForward",
        "BrowserBack",
        "LaunchApp1",
        "LaunchMail",
      ],
      description: "Key to press to go right",
      example: "ArrowRight",
      default: "ArrowRight",
    },
  ],
};
