import type { EditorComponentManifest } from "@nanoforge-dev/ecs-lib";
import { type InputEnum } from "@nanoforge-dev/input";

export class JumpController2D {
  name = this.constructor.name;
  public keyPressedLastFrame = false;
  public remainingJumps: number = 0;
  public coyoteTimer: number = 0;
  public bufferTimer: number = 0;

  constructor(
    public impulseStrength: number,
    public key: InputEnum,
    public maxJumps: number,
    public coyoteTime: number,
    public jumpBuffer: number,
  ) {
  }
}

// * Required to generate code
export default JumpController2D.name;

// * Required for the editor to display the component and generate code
export const EDITOR_COMPONENT_MANIFEST: EditorComponentManifest = {
  name: "JumpController2D",
  description: "Allow jump upwards",
  params: [
    {
      type: "number",
      name: "impulseStrength",
      description: "Speed going up in pixels per second",
      default: 100,
    },
    {
      name: "key",
      type: "string",
      enum: [
        "Escape",
        "Digit1",
        "Digit2",
        "Digit3",
        "Digit4",
        "Digit5",
        "Digit6",
        "Digit7",
        "Digit8",
        "Digit9",
        "Digit0",
        "Minus",
        "Equal",
        "Backspace",
        "Tab",
        "KeyQ",
        "KeyW",
        "KeyE",
        "KeyR",
        "KeyT",
        "KeyY",
        "KeyU",
        "KeyI",
        "KeyO",
        "KeyP",
        "BracketLeft",
        "BracketRight",
        "Enter",
        "ControlLeft",
        "KeyA",
        "KeyS",
        "KeyD",
        "KeyF",
        "KeyG",
        "KeyH",
        "KeyJ",
        "KeyK",
        "KeyL",
        "Semicolon",
        "Quote",
        "Backquote",
        "ShiftLeft",
        "Backslash",
        "KeyZ",
        "KeyX",
        "KeyC",
        "KeyV",
        "KeyB",
        "KeyN",
        "KeyM",
        "Comma",
        "Period",
        "Slash",
        "ShiftRight",
        "NumpadMultiply",
        "AltLeft",
        "Space",
        "CapsLock",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "Pause",
        "ScrollLock",
        "Numpad7",
        "Numpad8",
        "Numpad9",
        "NumpadSubtract",
        "Numpad4",
        "Numpad5",
        "Numpad6",
        "NumpadAdd",
        "Numpad1",
        "Numpad2",
        "Numpad3",
        "Numpad0",
        "NumpadDecimal",
        "IntlBackslash",
        "F11",
        "F12",
        "NumpadEqual",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "KanaMode",
        "Lang2",
        "Lang1",
        "IntlRo",
        "F24",
        "Convert",
        "NonConvert",
        "IntlYen",
        "NumpadComma",
        "MediaTrackPrevious",
        "MediaTrackNext",
        "NumpadEnter",
        "ControlRight",
        "AudioVolumeMute",
        "LaunchApp2",
        "MediaPlayPause",
        "MediaStop",
        "BrowserHome",
        "NumpadDivide",
        "PrintScreen",
        "AltRight",
        "NumLock",
        "Home",
        "ArrowUp",
        "PageUp",
        "ArrowLeft",
        "ArrowRight",
        "End",
        "ArrowDown",
        "PageDown",
        "Insert",
        "Delete",
        "MetaLeft",
        "MetaRight",
        "ContextMenu",
        "Power",
        "BrowserSearch",
        "BrowserFavorites",
        "BrowserRefresh",
        "BrowserStop",
        "BrowserForward",
        "BrowserBack",
        "LaunchApp1",
        "LaunchMail",
        "MouseLeft",
        "MouseMiddle",
        "MouseRight",
        "BackButton",
        "Forward"
      ],
      description: "Key to press to go up",
      example: "Space",
      default: "Space",
    },
    {
      type: "number",
      name: "maxJumps",
      description: "Max number of jump before touching the ground",
      default: 2,
    },
    {
      type: "number",
      name: "coyoteTime",
      description: "Time to jump afer exiting a cliff in s",
      default: 0.1,
    },
    {
      type: "number",
      name: "jumpBuffer",
      description: "Time before hitting the ground counting as a jump in s",
      default: 0.1,
    },

  ],
};
